<?php

namespace Med\CeliaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function findAllByLatest()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }
}
