<?php

namespace Proxies\__CG__\Med\CeliaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \Med\CeliaBundle\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'nom', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'recettes', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'nbRecette');
        }

        return array('__isInitialized__', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'nom', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'recettes', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Categorie' . "\0" . 'nbRecette');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function increaseNbRecette()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'increaseNbRecette', array());

        return parent::increaseNbRecette();
    }

    /**
     * {@inheritDoc}
     */
    public function decreaseNbRecette()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decreaseNbRecette', array());

        return parent::decreaseNbRecette();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbRecette($nbRecette)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbRecette', array($nbRecette));

        return parent::setNbRecette($nbRecette);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbRecette()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbRecette', array());

        return parent::getNbRecette();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecette(\Med\CeliaBundle\Entity\Recette $recettes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecette', array($recettes));

        return parent::addRecette($recettes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecette(\Med\CeliaBundle\Entity\Recette $recettes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecette', array($recettes));

        return parent::removeRecette($recettes);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecettes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecettes', array());

        return parent::getRecettes();
    }

}
