<?php

namespace Proxies\__CG__\Med\CeliaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Marque extends \Med\CeliaBundle\Entity\Marque implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'id', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'produits', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nomMarque', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nbProd', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nbProdAutorise');
        }

        return array('__isInitialized__', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'id', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'produits', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nomMarque', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nbProd', '' . "\0" . 'Med\\CeliaBundle\\Entity\\Marque' . "\0" . 'nbProdAutorise');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Marque $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function increaseNbProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'increaseNbProd', array());

        return parent::increaseNbProd();
    }

    /**
     * {@inheritDoc}
     */
    public function decreaseNbProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decreaseNbProd', array());

        return parent::decreaseNbProd();
    }

    /**
     * {@inheritDoc}
     */
    public function increaseNbProdAutorise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'increaseNbProdAutorise', array());

        return parent::increaseNbProdAutorise();
    }

    /**
     * {@inheritDoc}
     */
    public function decreaseNbProdAutorise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decreaseNbProdAutorise', array());

        return parent::decreaseNbProdAutorise();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMarque($nomMarque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMarque', array($nomMarque));

        return parent::setNomMarque($nomMarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMarque', array());

        return parent::getNomMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbProd($nbProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbProd', array($nbProd));

        return parent::setNbProd($nbProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbProd', array());

        return parent::getNbProd();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbProdAutorise($nbProdAutorise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbProdAutorise', array($nbProdAutorise));

        return parent::setNbProdAutorise($nbProdAutorise);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbProdAutorise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbProdAutorise', array());

        return parent::getNbProdAutorise();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduit(\Med\CeliaBundle\Entity\Produit $produits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduit', array($produits));

        return parent::addProduit($produits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduit(\Med\CeliaBundle\Entity\Produit $produits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduit', array($produits));

        return parent::removeProduit($produits);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduits', array());

        return parent::getProduits();
    }

}
